### PR TITLE
Update database

### PR DESCRIPTION
**Pull request by pdxJaxon**
New DB Backend with Sequelize and SQLite for now

### CODE REVIEW

**Comment by pdxJaxon** [comment]
ok.....I am pretty sure I got this correct now.....

I have fully rebased and did a git push --force origin MyBranch

Please let me know if I screwed anything up so I can fix.

WebApp is coming up on my local box and is serving "Teams" data via:
http://localhost:3001/teams

**Comment by toddrun** [comment]
This doesn't seem like it's rebased correctly since it's trying to replace just about every file (including the .gitignore file). It might be tough to get the PR in a clean state.

The easiest approach may be to:

- Checkout (and pull) master
- Create a new branch
- Cherry pick the 4 commits from this PR onto the new branch
- Create a new PR for the new branch

There are other options too . . . let me know if you want me to see if I can get this PR cleaned up.

**Comment by toddrun** [comment]
It may just be that master didn't get pulled before this branch got rebased. Might be worth trying again to see if that clears it up.

**Comment by pdxJaxon** [comment]
I think this PR is ready to roll.....I got rid of all the node_modules crap.

**Pull request closed without merging**
